"""Planning-only manager orchestration helpers for LangSOP IR8.

The exported models are pure records and validators. They do not dispatch
agents, execute commands, control processes or GPUs, mutate model runtimes,
access credentials, change networks, or authorize live machine control.
"""

from .authority import (
    ManagerAuthorityClassification,
    classify_manager_authority_from_mapping,
    classify_manager_record_authority,
    validate_manager_authority_classification,
)
from .faults import (
    ManagerFaultKind,
    ManagerFaultRecord,
    ManagerFaultSeverity,
    fault_kind_for_issue_kind,
    manager_fault_record_from_issue,
    manager_fault_records_from_readiness,
    safe_next_route_for_fault,
    validate_manager_fault_record,
)
from .handoffs import (
    HumanOverrideRecord,
    ManagerHandoffKind,
    ManagerHandoffRecord,
    ManagerHandoffStatus,
    ManagerRefusalRecord,
    handoff_record_from_readiness,
    human_override_record_from_parts,
    manager_handoff_record_from_parts,
    manager_refusal_record_from_issue,
    manager_refusal_records_from_readiness,
    safe_next_route_for_refusal,
    validate_human_override_record,
    validate_manager_handoff_record,
)
from .packets import (
    build_manager_work_packet_candidate,
    packet_is_claimable,
)
from .readiness import (
    recompute_manager_readiness,
    recompute_manager_readiness_from_mapping,
)
from .records import (
    NO_DISPATCH_NOTICE,
    NO_LIVE_EFFECT_NOTICE,
    SOP_INTERRUPT_NOTICE,
    CompletionGate,
    ManagerAuthorityClass,
    ManagerCycleInput,
    ManagerFreshnessState,
    ManagerIssue,
    ManagerIssueKind,
    ManagerIssueSeverity,
    ManagerModelRoute,
    ManagerReadinessResult,
    ManagerReadinessState,
    ManagerWorkPacketState,
    ProofObligation,
    SOPFirstManagerInterruptContext,
    WorkPacketCandidate,
    completion_gate_for_cycle,
    manager_cycle_input_from_mapping,
    manager_cycle_input_from_parts,
    proof_obligations_for_cycle,
)

__all__ = (
    "NO_DISPATCH_NOTICE",
    "NO_LIVE_EFFECT_NOTICE",
    "SOP_INTERRUPT_NOTICE",
    "CompletionGate",
    "ManagerAuthorityClass",
    "ManagerAuthorityClassification",
    "ManagerCycleInput",
    "ManagerFaultKind",
    "ManagerFaultRecord",
    "ManagerFaultSeverity",
    "ManagerFreshnessState",
    "ManagerHandoffKind",
    "ManagerHandoffRecord",
    "ManagerHandoffStatus",
    "ManagerIssue",
    "ManagerIssueKind",
    "ManagerIssueSeverity",
    "ManagerModelRoute",
    "ManagerRefusalRecord",
    "ManagerReadinessResult",
    "ManagerReadinessState",
    "ManagerWorkPacketState",
    "ProofObligation",
    "SOPFirstManagerInterruptContext",
    "WorkPacketCandidate",
    "build_manager_work_packet_candidate",
    "classify_manager_authority_from_mapping",
    "classify_manager_record_authority",
    "completion_gate_for_cycle",
    "fault_kind_for_issue_kind",
    "handoff_record_from_readiness",
    "human_override_record_from_parts",
    "manager_fault_record_from_issue",
    "manager_fault_records_from_readiness",
    "manager_handoff_record_from_parts",
    "manager_cycle_input_from_mapping",
    "manager_cycle_input_from_parts",
    "manager_refusal_record_from_issue",
    "manager_refusal_records_from_readiness",
    "packet_is_claimable",
    "proof_obligations_for_cycle",
    "recompute_manager_readiness",
    "recompute_manager_readiness_from_mapping",
    "safe_next_route_for_fault",
    "safe_next_route_for_refusal",
    "validate_human_override_record",
    "validate_manager_authority_classification",
    "validate_manager_fault_record",
    "validate_manager_handoff_record",
)
