"""Dry-run-only operation planning helpers for LangSOP IR7.

The exported models are projection records and validators only. They provide
no command execution, process control, GPU control, job dispatch, credential
access, network mutation, destructive filesystem action, operations control,
or live machine control.
"""

from .dry_run import (
    NON_AUTHORITY_NOTICE,
    DryRunResultIssue,
    DryRunResultIssueKind,
    DryRunResultIssueSeverity,
    DryRunResultRecord,
    DryRunResultStatus,
    DryRunResultValidation,
    dry_run_result_from_operation_request,
    dry_run_result_record_from_mapping,
    dry_run_result_record_from_parts,
    validate_dry_run_result_record,
)
from .refusals import (
    INTERRUPT_NON_AUTHORITY_NOTICE,
    REFUSAL_NON_AUTHORITY_NOTICE,
    OperationRefusalOutput,
    OperationRefusalReason,
    OperationRefusalRecord,
    OperationRefusalValidation,
    OperationRefusalValidationIssue,
    OperationRefusalValidationIssueKind,
    OperationRefusalValidationSeverity,
    SOPFirstInterruptContext,
    evidence_ref_set_for_validation,
    refusal_output_set_for_request,
    refusal_reason_for_issue,
    refusal_record_from_request_validation,
    safe_next_route_for_reason,
    sop_first_interrupt_context_from_refusal,
    validate_operation_refusal_record,
)
from .requests import (
    BLOCKED_LIVE_EFFECT_SET,
    HIGH_RISK_TARGET_SET,
    REQUIRED_OPERATION_REQUEST_IDENTITY_FIELD_SET,
    REQUIRED_OPERATION_REQUEST_SAFETY_FIELD_SET,
    SAFE_DRY_RUN_EFFECT_SET,
    TARGET_KIND_SET,
    OperationAuthorityTier,
    OperationEffectClass,
    OperationFreshnessState,
    OperationRequestEnvelope,
    OperationRequestIssueKind,
    OperationRequestIssueSeverity,
    OperationRequestStatus,
    OperationRequestValidationIssue,
    OperationRequestValidationResult,
    OperationTargetRisk,
    classify_intended_effect,
    classify_resource_target,
    operation_request_envelope_from_mapping,
    operation_request_envelope_from_parts,
    operation_request_status_for_issues,
    validate_operation_request_envelope,
)

__all__ = (
    "BLOCKED_LIVE_EFFECT_SET",
    "HIGH_RISK_TARGET_SET",
    "INTERRUPT_NON_AUTHORITY_NOTICE",
    "NON_AUTHORITY_NOTICE",
    "REFUSAL_NON_AUTHORITY_NOTICE",
    "REQUIRED_OPERATION_REQUEST_IDENTITY_FIELD_SET",
    "REQUIRED_OPERATION_REQUEST_SAFETY_FIELD_SET",
    "SAFE_DRY_RUN_EFFECT_SET",
    "TARGET_KIND_SET",
    "DryRunResultIssue",
    "DryRunResultIssueKind",
    "DryRunResultIssueSeverity",
    "DryRunResultRecord",
    "DryRunResultStatus",
    "DryRunResultValidation",
    "OperationAuthorityTier",
    "OperationEffectClass",
    "OperationFreshnessState",
    "OperationRefusalOutput",
    "OperationRefusalReason",
    "OperationRefusalRecord",
    "OperationRefusalValidation",
    "OperationRefusalValidationIssue",
    "OperationRefusalValidationIssueKind",
    "OperationRefusalValidationSeverity",
    "OperationRequestEnvelope",
    "OperationRequestIssueKind",
    "OperationRequestIssueSeverity",
    "OperationRequestStatus",
    "OperationRequestValidationIssue",
    "OperationRequestValidationResult",
    "OperationTargetRisk",
    "SOPFirstInterruptContext",
    "classify_intended_effect",
    "classify_resource_target",
    "dry_run_result_from_operation_request",
    "dry_run_result_record_from_mapping",
    "dry_run_result_record_from_parts",
    "evidence_ref_set_for_validation",
    "operation_request_envelope_from_mapping",
    "operation_request_envelope_from_parts",
    "operation_request_status_for_issues",
    "refusal_output_set_for_request",
    "refusal_reason_for_issue",
    "refusal_record_from_request_validation",
    "safe_next_route_for_reason",
    "sop_first_interrupt_context_from_refusal",
    "validate_dry_run_result_record",
    "validate_operation_refusal_record",
    "validate_operation_request_envelope",
)
